name: Build spacebar client docker image

on:
  push:
    branches: ["master"]
    paths:
      - "spacebar-client/**"
  pull_request:
    branches: ["master"]
    paths:
      - "spacebar-client/**"
  workflow_dispatch:
    inputs:
      push:
        description: "Push to Docker Hub"
        required: true
        default: false
        type: boolean
      arm:
        description: "Build ARM64"
        required: true
        default: true
        type: boolean
      amd:
        description: "Build AMD64"
        required: true
        default: true
        type: boolean

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    if: ${{ inputs.amd }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_SPACEBAR_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SPACEBAR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:spacebar-client/"
          platforms: linux/amd64
          file: Dockerfile
          push: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push) }}
          tags: spacebarchat/client:latest-amd64
          provenance: false
      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: spacebarchat/client:latest
          images: spacebarchat/client:latest-amd64
          push: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push) }}
          amend: true

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_SPACEBAR_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SPACEBAR_TOKEN }}
      - name: Build and push armv7
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:spacebar-client/"
          platforms: linux/arm/v7
          file: Dockerfile
          push: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push) }}
          tags: spacebarchat/client:latest-armv7
          provenance: false
      - name: Build and push arm64
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:spacebar-client/"
          platforms: linux/arm64
          file: Dockerfile
          push: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push) }}
          tags: spacebarchat/client:latest-arm64
          provenance: false
